replicaCount: 1

redis:
  fullnameOverride: ""
  image:
    repository: redis
    tag: latest
  service:
    type: ClusterIP
    port: 6379
  containerPort: 6379
  ingress:
    enabled: false

server:
  fullnameOverride: ""
  strategy:
    type: RollingUpdate
  image:
    repository: twentycrm/twenty
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
    host: ""
  env:
    secretsRef: "twenty-crm-secrets"


worker:
  fullnameOverride: ""
  strategy:
    type: RollingUpdate
  image:
    repository: twentycrm/twenty
    tag: latest
    pullPolicy: IfNotPresent
  command: ["yarn", "worker:prod"]
  ingress:
    enabled: false
  env:
    secretsRef: "twenty-crm-secrets"

postgresql:
  image:
    repository: twentycrm/twenty-postgres-spilo
    tag: latest
  service:
    type: ClusterIP
    port: 5432
  env:
    secretsRef: "twenty-crm-secrets"
    
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
