replicaCount: 1

redis:
  fullnameOverride: ""
  image:
    repository: redis
    tag: latest
  service:
    type: ClusterIP
    port: 6379
  containerPort: 6379
  ingress:
    enabled: false

server:
  fullnameOverride: ""
  strategy:
    type: RollingUpdate
  image:
    repository: twentycrm/twenty
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3000
    nodePort: 32000  # Specify a static NodePort
  ingress:
    enabled: false
  env:
    variables:
      SERVER_URL: "http://192.168.122.36:32000"  # Update to use the static NodePort
      REDIS_URL: "redis://twenty-twenty-redis:6379"
      SIGN_IN_PREFILLED: "false"
      STORAGE_TYPE: "local"
      STORAGE_S3_REGION: "us-east-1"
      STORAGE_S3_NAME: "webpointtwenty"
      STORAGE_S3_ENDPOINT: ""
      APP_SECRET: "YGbOICvScZtfLjVpabRNh6NPjqdef1CDyDRFKqoEAos="

worker:
  fullnameOverride: ""
  strategy:
    type: RollingUpdate
  image:
    repository: twentycrm/twenty
    tag: latest
    pullPolicy: IfNotPresent
  command: ["yarn", "worker:prod"]
  ingress:
    enabled: false
  env:
    variables:
      PG_DATABASE_URL: "postgres://postgres:password123@twenty-postgresql:5432/default"
      SERVER_URL: "http://192.168.122.36:32000"
      REDIS_URL: "redis://twenty-twenty-redis:6379"
      SIGN_IN_PREFILLED: "false"
      STORAGE_TYPE: "local"
      STORAGE_S3_REGION: "us-east-1"
      STORAGE_S3_NAME: "webpointtwenty"
      STORAGE_S3_ENDPOINT: ""
      APP_SECRET: "YGbOICvScZtfLjVpabRNh6NPjqdef1CDyDRFKqoEAos="

postgresql:
  image:
    repository: twentycrm/twenty-postgres-spilo
    tag: latest
  service:
    type: ClusterIP
    port: 5432
  env:
    variables:
      PGUSER_SUPERUSER: "postgres"
      PGPASSWORD_SUPERUSER: "password123"
      ALLOW_NOSSL: "true"
      SPILO_PROVIDER: "local"
    
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
