apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-manager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: app
    repoURL: git@github.com:Sulav-Adhikari/argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true