apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80       # target port and port value are set to same 
      targetPort: 80 #port on which application is running
      nodePort: 31110

