# Values for deployment 

labels: npx
containerName: npx
replicaCount: 2
revisionHistoryLimit: 2 #rollout

image: 
  repository: sulavadk7/private
  imagePullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "npx-v"
  
imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""


service: 
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 31118

