# Values for deployment 

labels: npx
containerName: npx
replicaCount: 1

image: 
  repository: sulavadk7/private
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "npx-v"
  
imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""


#values for service

service: 
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 31117

