apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: main=docker.io/sulavadk7/private
    argocd-image-updater.argoproj.io/main.update-strategy: latest
    argocd-image-updater.argoproj.io/main.allow-tags: regexp:^npx-v[0-9]+\.[0-9]+\.[0-9]+$

spec:
  project: default

  source:
    repoURL: git@github.com:Sulav-Adhikari/argocd.git
    targetRevision: main
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: npx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
