apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  annotations:
    argocd-image-updater.argoproj.io/image-list: main=sulavadk7/private:npx-v1.0.2
    argocd-image-updater.argoproj.io/main.update-strategy: latest
    argocd-image-updater.argoproj.io/main.pull-secret: pullsecret:argocd/dockerconfigjson
    argocd-image-updater.argoproj.io/main.allow-tags: ^npx-v[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/main.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/main.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-repo-pat
    argocd-image-updater.argoproj.io/git-branch: main  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  
  
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:Sulav-Adhikari/argocd.git
    targetRevision: main
    path: dev

    helm: 
      values: |
        image:
          repository: sulavadk7/private
          tag: npx-v1.0.2
        
        service: 
          port: 3000
          targetPort: 3000
          nodePort: 31117

        imagePullSecrets:
         - name : dockerconfigjson


  destination: 
    server: https://kubernetes.default.svc
    namespace: npx

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
