apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twenty-crm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:webpoint-solutions-llc/gitops-internals.git
    targetRevision: main
    path: charts/common/twenty
  helm:
    values: |
      server:
        image:
          repository: twentycrm/twenty
          tag: latest
        ingress:
          host: "twenty.webpoint.io"

      worker:
        image:
          repository: twentycrm/twenty
          tag: latest
      
      redis:
        image:
          repository: redis
          tag: latest

      postgresql:
        image:
          repository: twentycrm/twenty-postgres-spilo
          tag: latest
  destination:
    name: in-cluster
    namespace: tools
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true