apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-postgresql
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.postgresql.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
