apiVersion: v1
kind: Service
metadata:
  name: {{ include "twenty.fullname" . }}
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.server.service.nodePort }}  # Use the static NodePort
  selector:
    {{- include "twenty.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twenty.fullname" . }}-redis
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "twenty.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: twenty-postgresql
  labels:
    {{- include "twenty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      protocol: TCP
      name: postgresql
  selector:
    app: {{ include "twenty.name" . }}
    component: postgresql
